import Icon from "../assets/images/machine-icon1.svg";
import successIcon from "../assets/images/success-icon.svg";
import failureIcon from "../assets/images/failure-icon.svg";
import pendingIcon from "../assets/images/pending-icon.svg";
import refundInitiatedIcon from "../assets/images/refund-initiated-icon.svg";
import refundCompletedIcon from "../assets/images/refund-icon.svg";
import sentIcon from "../assets/images/sent-icon.svg";
import homeIcon from "../assets/images/home-icon.svg";
import mapIcon from "../assets/images/map-icon.svg";
import allOrdersIcon from "../assets/images/org-icon.svg";
import usersIcon from "../assets/images/users-icon.svg";
import foodIcon from "../assets/images/food-icon.svg";
import ordersIcon from "../assets/images/orders-icon.svg";
import offersIcon from "../assets/images/offers-icon.svg";
import settingsIcon from "../assets/images/settings-icon.svg";
import logoutIcon from "../assets/images/logout-icon.svg";
import { menuInterface, statusInterface } from "../interfaces/interfaces";
import drink1 from "../assets/images/drink1.svg";
import drink2 from "../assets/images/drink2.svg";
import drink3 from "../assets/images/drink3.svg";

export const ordersList = {
  orders: [
    {
      date: "01/01/2024 08:00:00",
      orderId: "OD101",
      machineName: "Machine A",
      user: {
        f_name: "John",
        l_name: "Doe",
        phone: "123-456-7890",
        age: 23,
        id: "MI101",
        email: "h7cJt@example.com",
      },
      totalAmount: 200,
      status: "Pending",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "02/01/2024 09:30:00",
      orderId: "OD102",
      machineName: "Machine B",
      user: {
        f_name: "Alice",
        l_name: "Smith",
        phone: "987-654-3210",
        age: 30,
        id: "MI102",
        email: "h7cJt@example.com",
      },
      totalAmount: 350,
      status: "Success",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "03/01/2024 10:45:00",
      orderId: "OD103",
      machineName: "Machine C",
      user: {
        f_name: "Emily",
        l_name: "Jones",
        phone: "456-789-0123",
        age: 28,
        id: "MI103",
        email: "h7cJt@example.com",
      },
      totalAmount: 550,
      status: "Refund Completed",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "04/01/2024 12:00:00",
      orderId: "OD104",
      machineName: "Machine A",
      user: {
        f_name: "Michael",
        l_name: "Brown",
        phone: "111-222-3333",
        age: 25,
        id: "MI104",
        email: "h7cJt@example.com",
      },
      totalAmount: 420,
      status: "Refund Initiated",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "05/01/2024 13:15:00",
      orderId: "OD105",
      machineName: "Machine B",
      user: {
        f_name: "Sophia",
        l_name: "Wilson",
        phone: "444-555-6666",
        age: 35,
        id: "MI105",
        email: "h7cJt@example.com",
      },
      totalAmount: 280,
      status: "Failure",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "06/01/2024 14:30:00",
      orderId: "OD106",
      machineName: "Machine C",
      user: {
        f_name: "Daniel",
        l_name: "Taylor",
        phone: "777-888-9999",
        age: 29,
        id: "MI106",
        email: "h7cJt@example.com",
      },
      totalAmount: 600,
      status: "Sent",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "07/01/2024 15:45:00",
      orderId: "OD107",
      machineName: "Machine A",
      user: {
        f_name: "Olivia",
        l_name: "Martinez",
        phone: "000-111-2222",
        age: 27,
        id: "MI107",
        email: "h7cJt@example.com",
      },
      totalAmount: 320,
      status: "Success",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "08/01/2024 16:00:00",
      orderId: "OD108",
      machineName: "Machine B",
      user: {
        f_name: "Liam",
        l_name: "Garcia",
        phone: "333-444-5555",
        age: 31,
        id: "MI108",
        email: "h7cJt@example.com",
      },
      totalAmount: 470,
      status: "Pending",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: "",
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Refund",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Refund",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },

        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },

        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "09/01/2024 17:15:00",
      orderId: "OD109",
      machineName: "Machine C",
      user: {
        f_name: "Ava",
        l_name: "Rodriguez",
        phone: "666-777-8888",
        age: 26,
        id: "MI109",
        email: "h7cJt@example.com",
      },
      totalAmount: 390,
      status: "Refund Completed",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: "",
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Refund",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Refund",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },

        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },

        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "10/01/2024 18:30:00",
      orderId: "OD110",
      machineName: "Machine A",
      user: {
        f_name: "Noah",
        l_name: "Lopez",
        phone: "999-000-1111",
        age: 33,
        id: "MI110",
        email: "h7cJt@example.com",
      },
      totalAmount: 520,
      status: "Failure",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: "",
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Refund",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Refund",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },

        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },

        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: "",
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "11/01/2024 19:45:00",
      orderId: "OD111",
      machineName: "Machine B",
      user: {
        f_name: "Emma",
        l_name: "Hernandez",
        phone: "222-333-4444",
        age: 24,
        id: "MI111",
        email: "h7cJt@example.com",
      },
      totalAmount: 680,
      status: "Sent",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "12/01/2024 20:00:00",
      orderId: "OD112",
      machineName: "Machine C",
      user: {
        f_name: "William",
        l_name: "King",
        phone: "555-666-7777",
        age: 32,
        id: "MI112",
        email: "h7cJt@example.com",
      },
      totalAmount: 450,
      status: "Success",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "13/01/2024 21:15:00",
      orderId: "OD113",
      machineName: "Machine A",
      user: {
        f_name: "Mia",
        l_name: "Young",
        phone: "888-999-0000",
        age: 30,
        id: "MI113",
        email: "h7cJt@example.com",
      },
      totalAmount: 320,
      status: "Pending",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
    {
      date: "14/01/2024 22:30:00",
      orderId: "OD114",
      machineName: "Machine B",
      user: {
        f_name: "James",
        l_name: "Lopez",
        phone: "111-222-3333",
        age: 28,
        id: "MI114",
        email: "h7cJt@example.com",
      },
      totalAmount: 540,
      status: "Refund Initiated",
      orderDetails: [
        {
          id: "C101",
          drinkName: "Mix Berry Smoothie",
          drinkImg: `${drink1}`,
          customisation: "Low Honey",
          amount: 233,
          drinkStatus: "Pending",
          action: "Refund",
        },
        {
          id: "C102",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Success",
          action: "Reorder",
        },
        {
          id: "C103",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Failure",
          action: "Reorder",
        },
        {
          id: "C104",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Initiated",
          action: "Refund",
        },
        {
          id: "C105",
          drinkName: "Coca Cola",
          drinkImg: `${drink2}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
        {
          id: "C106",
          drinkName: "Coca Cola",
          drinkImg: `${drink1}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Refund Completed",
          action: "Refund",
        },
        {
          id: "C107",
          drinkName: "Coca Cola",
          drinkImg: `${drink3}`,
          customisation: "Medium",
          amount: 100,
          drinkStatus: "Sent",
          action: "Refund",
        },
      ],
    },
  ],
};

export const ordersStats = {
  machines: 6,
  orders: 6,
  customers: 6,
  drinks: 6,
  totalAmount: 25999,
  refundsInitiated: 3,
};

export const filterList = {
  filters: [
    {
      machineName: {
        name: "Aahaar Stall",
        no: 23,
        id: "MI101",
        icon: `${Icon}`,
      },
      address: "Aahaar Stall 10, Pragati Maidan, New Delhi",
    },
    {
      machineName: {
        name: "Aahaar Stall",
        no: 33,
        id: "MI102",
        icon: `${Icon}`,
      },
      address: "Aahaar Stall 20, Pragati Maidan, New Delhi",
    },
    {
      machineName: {
        name: "Aahaar Stall",
        no: 43,
        id: "MI103",
        icon: `${Icon}`,
      },
      address: "Aahaar Stall 30, Pragati Maidan, New Delhi",
    },
    {
      machineName: {
        name: "Aahaar Stall",
        no: 53,
        id: "MI104",
        icon: `${Icon}`,
      },
      address: "Aahaar Stall 40, Pragati Maidan, New Delhi",
    },
    {
      machineName: {
        name: "Aahaar Stall",
        no: 63,
        id: "MI105",
        icon: `${Icon}`,
      },
      address: "Aahaar Stall 50, Pragati Maidan, New Delhi",
    },
    {
      machineName: {
        name: "Aahaar Stall",
        no: 73,
        id: "MI106",
        icon: `${Icon}`,
      },
      address: "Aahaar Stall 60, Pragati Maidan, New Delhi",
    },
    {
      machineName: {
        name: "Aahaar Stall",
        no: 83,
        id: "MI107",
        icon: `${Icon}`,
      },
      address: "Aahaar Stall 70, Pragati Maidan, New Delhi",
    },
    {
      machineName: {
        name: "Aahaar Stall",
        no: 93,
        id: "MI108",
        icon: `${Icon}`,
      },
      address: "Aahaar Stall 80, Pragati Maidan, New Delhi",
    },
    {
      machineName: {
        name: "Aahaar Stall",
        no: 103,
        id: "MI109",
        icon: `${Icon}`,
      },
      address: "Aahaar Stall 90, Pragati Maidan, New Delhi",
    },
  ],
};

export const status: statusInterface[] = [
  { label: "Successful", img: `${successIcon}` },
  { label: "Pending", img: `${pendingIcon}` },
  { label: "Sent", img: `${sentIcon}` },
  { label: "Failure", img: `${failureIcon}` },
  { label: "Refund Initiated", img: `${refundInitiatedIcon}` },
  { label: "Refund Completed", img: `${refundCompletedIcon}` },
];

export const menuLinks: menuInterface[] = [
  { url: "/home", img: `${homeIcon}`, alt: "Home Icon" },
  { url: "/map", img: `${mapIcon}`, alt: "Map Icon" },
  { url: "/orders", img: `${allOrdersIcon}`, alt: "Orders Icon" },
  { url: "/users", img: `${usersIcon}`, alt: "Users Icon" },
  { url: "/food", img: `${foodIcon}`, alt: "Food Icon" },
  { url: "/menu", img: `${ordersIcon}`, alt: "Menu Icon" },
  { url: "/offers", img: `${offersIcon}`, alt: "Offers Icon" },
  { url: "/settings", img: `${settingsIcon}`, alt: "Settings Icon" },
  { url: "/logout", img: `${logoutIcon}`, alt: "Logout Icon" },
];
